export const API_REQUEST_SEND = 'API_REQUEST_SEND';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';
//auth
export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const AUTH_POST_TOKEN = 'AUTH_POST_TOKEN';
export const AUTH_POST_CHANGE_PASSWORD = 'AUTH_POST_CHANGE_PASSWORD';
